# Generated by Django 5.1.6 on 2025-05-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_dronelog_user_telemetrylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronelog',
            name='drone_model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='dronelog',
            name='exhibit_no',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='drone_model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='exhibit_no',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
