# Generated by Django 5.1.6 on 2025-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_dronelog_drone_model_dronelog_exhibit_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronelog',
            name='exhibit_no',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='exhibit_no',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
